apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-comparator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-comparator
  template:
    metadata:
      labels:
        app: flight-comparator
    spec:
      containers:
        - name: flight-comparator
          image: 162582596521.dkr.ecr.eu-west-1.amazonaws.com/flight-comparator:latest
          ports:
            - containerPort: 8080
