apiVersion: v1
kind: Service
metadata:
  name: flight-comparator-service
spec:
  selector:
    app: flight-comparator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
